### ISSUE TITLE
CA Certs still not 'comprehensive'

### ISSUE THREAD

**Issue by michael-robbins** [hikhvar/mqtt2prometheus#48] opened 2021-03-07 02:58 UTC
So this might not be an issue, and feel free to just close if you think what's currently there is good enough and my workaround is something the user can easily do (maybe a doco update to help future users).

This still can't connect directly to my mosquitto mqtt broker with TLS enabled through Letsencrypt.

I've had to mount in my local servers cacerts file and overwrite the one in the image to get it to connect successfully.

```
--volume "/etc/ssl/certs/ca-certificates.crt:/etc/ssl/certs/ca-certificates.crt:ro"
```

This just allowed it to connect automatically using Ubuntu 20.04's default ca certs (I'm not doing anything special here, just default everything afaik).

I'm not totally sure of the solution here thought that could easily fix this without me having to mount in Ubuntu's certs to trust letsencrypt?

**Comment by michael-robbins** [comment] 2021-03-07 03:10
Actually this is even weirder, if I clone your master branch, and `docker build` it myself, no changes, it will then just work, but using the `latest` tag on your image results in the CA cert issues...

Is your docker hub image.. updated? Confused a bit here...

**Comment by hikhvar** [comment] 2021-03-07 06:01
I'm also confused. Maybe this is a caching issue with github actions 🤔 I have to cross check the images. Which platform you are running on? x86-64 or some ARM?

**Comment by hikhvar** [comment] 2021-03-08 18:54
Ok, I can reproduce the issue. 
```
# podman pull hikhvar/mqtt2prometheus:v0.1.6-RC3
Completed short name "hikhvar/mqtt2prometheus" with unqualified-search registries (origin: /etc/containers/registries.conf)
Trying to pull docker.io/hikhvar/mqtt2prometheus:v0.1.6-RC3...
Getting image source signatures
Copying blob ceb57c41191b done  
Copying config dbf6a1e86b done  
Writing manifest to image destination
Storing signatures
dbf6a1e86baad4a0866187d2957f636edf87c05eed4ef4373039e91ac35f34e6

# podman image mount hikhvar/mqtt2prometheus:v0.1.6-RC3
/home/christoph/.local/share/containers/storage/vfs/dir/ba0899329a170cd4015a126894bd54df6c958209b1e50298b09e4d88cd0629a1

 # cd /home/christoph/.local/share/containers/storage/vfs/dir/ba0899329a170cd4015a126894bd54df6c958209b1e50298b09e4d88cd0629a1

 # ls
mqtt2prometheus
```

If build from source:
```
# podman build -t mqtt2prometheus .
[....]
podman build -t mqtt2prometheus .  188,29s user 83,41s system 116% cpu 3:52,83 total

 # podman image mount localhost/mqtt2prometheus
/home/christoph/.local/share/containers/storage/vfs/dir/a87e6d96f636408fea55efd8e0fe314389e10bc61c4a62404781c39427f514f5

# cd /home/christoph/.local/share/containers/storage/vfs/dir/a87e6d96f636408fea55efd8e0fe314389e10bc61c4a62404781c39427f514f5

# ls
bin  boot  dev  etc  home  lib  mqtt2prometheus  proc  root  run  sbin  sys  tmp  usr  var
```

I see that the base image layer is missing in the published image. goreleaser (the tool used for the releases) uses `docker buildx` internally. I will try to reproduce the issue with buildx.

**Comment by michael-robbins** [comment] 2021-03-08 21:32
Hey sorry had a busy weekend, yeah just bog standard x86-64 servers, nothing fancy.

Ok I can kinda see where you're getting at here, using the docker hub image we're missing all the other directories, including things like the CA certs/etc, which explain the problem here.

Thanks for troubleshooting this, I should have inspected the images more thoroughly and seen the missing filesystem folders/etc before!

I'll keep an eye out for RC4 and give that a whirl this week when I get a minute :)

**Comment by hikhvar** [comment] 2021-03-08 21:43
I'm currently into it. The main problem is currently finding a base image to support those architectures:
```
"386"
"amd64"
"armv6"
"arm64"
"armv7"
"riscv64"
```
I would like to have a `riscv64` image just to have one :-D (it's a hobby project after all), but I think I must drop that since non of the big distros ships such a base image.

**Comment by hikhvar** [comment] 2021-03-08 22:29
Can you please test the [v0.1.6-RC5 ](https://github.com/hikhvar/mqtt2prometheus/releases/tag/v0.1.6-RC5 ) release? I checked the image, it contains the proper certificate files (`/etc/ssl/certs/ca-certificates.crt`).

**Comment by michael-robbins** [comment] 2021-03-09 01:35
Yep I've pulled `latest` and that works fine! No issues at all connecting, can see all the metrics! Wooo 🎉 

You could have a different build pipeline(s) to produce `riscv64` image(s) separately? Maybe bake in CA certs some other way?

**Comment by michael-robbins** [comment] 2021-03-09 01:37
You could build it with scratch and just call out that it's a 'second class citizen' re: CA certs/etc

**Comment by hikhvar** [comment] 2021-03-09 07:48
There are more urgent tasks to do than a riscv64 image ;) E.g. the documentation.
I will close this issue for now.

**Closed by hikhvar** 2021-03-09 07:48 UTC
